language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pipenv
install:
    - pipenv install --dev
script:
    - coverage run --source=. -m pytest
after_success:
    - coveralls
